version: '3.8'

services:

  redis:
    image: redis:7
    container_name: weather_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:14
    container_name: weather_pg
    environment:
      POSTGRES_USER: iguana
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Weather
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase_migration
    depends_on:
      - postgres
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    command:
      [
        "--changeLogFile=changelog/changelog-master.xml",
        "--url=jdbc:postgresql://postgres:5432/Weather",
        "--username=iguana",
        "--password=postgres",
        "--driver=org.postgresql.Driver",
        "update"
      ]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: weather_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: weather_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    ports:
      - "8080:8080"
    environment:
      YANDEX_API: ${YANDEX_API}
      METEO_API: ${METEO_API}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Weather
      SPRING_DATASOURCE_USERNAME: iguana
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - liquibase
      - kafka

volumes:
  pg_data:
  redis_data:
