spring:
  application:
    name: WeatherServiceSpringBoot

  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5433/Weather
    username: iguana
    password: postgres
    driverClassName: org.postgresql.Driver
