spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: weather-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.ArrayList


  application:
    name: WeatherServiceSpringBoot

  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml

  jpa:
    properties:
      '[hypersistence.utils.enable_types_contributor]': false
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  sql:
    init:
      platform: postgres

  datasource:
    url: jdbc:postgresql://localhost:5433/Weather
    username: ${SPRING_DATASOURCE_USERNAME:iguana}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

  cache:
    type: caffeine

api:
  token:
    yandex: ${YANDEX_API}
    meteo: ${METEO_API}
  url:
    yandex: https://geocode-maps.yandex.ru/v1/
    meteo: https://projecteol.ru/api/weather/

kafka:
  topic:
    city-update: weather-update-cities



